version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGODB_URI: ${MONGODB_URI}
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
        BETTER_AUTH_URL: ${BETTER_AUTH_URL}
        HACKCLUB_CLIENT_ID: ${HACKCLUB_CLIENT_ID}
        HACKCLUB_CLIENT_SECRET: ${HACKCLUB_CLIENT_SECRET}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        AWS_REGION: ${AWS_REGION}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
        AWS_ENDPOINT_URL_S3: ${AWS_ENDPOINT_URL_S3}
        AWS_FORCE_PATH_STYLE: ${AWS_FORCE_PATH_STYLE}
        AWS_S3_PUBLIC_URL: ${AWS_S3_PUBLIC_URL}
    env_file:
      - .env
    ports:
      - "4555:3000"
